{% set name = "tinysegmenter" %}
{% set version = "0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tinysegmenter-{{ version }}.tar.gz
  sha256: 64458bdba54ba7482c02c785f960cf3d6cf61594a4dab3d64c325439094fc1b7

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - tinysegmenter
  commands:
    - pip check
    - python tests/test.py
  requires:
    - pip
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: http://tinysegmenter.tuxfamily.org/
  summary: Very compact Japanese tokenizer
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - BastianZim
